### ISSUE TITLE
Matlab plot titles and legends render underscore as subscript

### ISSUE THREAD

**Issue by wigging** [davidhowey/SLIDE#2]
Titles, legends, and other labels in the Matlab figures render the `IDs` as a subscript because the text contains an `_` underscore. For example, the following

https://github.com/davidhowey/SLIDE/blob/ecd87fabed345ed366c4ae84144b610f21d3ae13/scipts/readAgeing_cyclingData.m#L129

should be changed to something like 

```matlab
title(strcat('cell temperature of ', IDs{i}))  
title(['cell temperature of ', IDs{I}], 'Interpreter', 'none')
```

Also, the `scipts` folder is mispelled; it should be `scripts`.

**Comment by ElektrikAkar** [comment]
Hi Gavin, 

It is very nice to hear your further feedback! I am sorry for the late reply. I have fixed the problem in all files under `ReadCycleAgeing.m`. Since it is not an emergency, I would like to check other files in future. However, I would be grateful if you could directly contribute via pull request in case of any further similar problems. I also understand that it would be very difficult this time since the typo in the folder name was obscuring seeing changes in scripts. Many thanks.

**Comment by wigging** [comment]
Ok, I'll run the latest code in the develop branch. I will submit a pull request if I find any more underscore issues in the Matlab figures.

**Comment by wigging** [comment]
I ran the `ReadCalendarAgeing.m`, `ReadCCCV.m`, `ReadCycleAgeing.m`, `ReadFollowCurrent.m` scripts and all the figure titles and labels look fine. So feel free to close this issue unless there is something else to discuss.
